const GET_PROJECTS = "GET_PROJECTS"
const ADD_PROJECT_ACTION = "ADD_PROJECT"
const DELETE_PROJECT_ACTION = "DELETE_PROJECT"
const UPDATE_PROJECT_ACTION = "UPDATE_PROJECT"

export { GET_PROJECTS, ADD_PROJECT_ACTION, DELETE_PROJECT_ACTION, UPDATE_PROJECT_ACTION }