const GET_PROJECTS = "GET_PROJECTS"
const ADD_PROJECT_ACTION = "ADD_PROJECT"
const DELETE_PROJECT_ACTION = "DELETE_PROJECT"
const UPDATE_PROJECT_ACTION = "UPDATE_PROJECT"

const GET_TASKS = "GET_TASKS"
const ADD_TASK = "ADD_TASK"
const DELETE_TASK = "DELETE_TASK"
const UPDATE_TASK_ACTION = "UPDATE_TASK"


export { 
    GET_PROJECTS, 
    ADD_PROJECT_ACTION, 
    DELETE_PROJECT_ACTION, 
    UPDATE_PROJECT_ACTION,
    GET_TASKS,
    ADD_TASK,
    DELETE_TASK,
    UPDATE_TASK_ACTION
    }   

