const ADD_PROJECT ='ADD_PROJECT'
const UPDATE_PROJECT = 'UPDATE_PROJECT'
const DELETE_PROJECT = 'DELETE_PROJECT'
const DEFINY_PROJECTS = 'DEFINY_PROJECTS'

const NOTIFY = 'NOTIFY'

const DEFINY_TASK = "DEFINY_TASKS"
const ADD_TASK_MUTATION = "ADD_TASK_MUTATION"

export { 
    ADD_PROJECT, 
    UPDATE_PROJECT, 
    DELETE_PROJECT, 
    NOTIFY, 
    DEFINY_PROJECTS,
    DEFINY_TASK,
    ADD_TASK_MUTATION
   }

   