const ADD_PROJECT ='ADD_PROJECT'
const UPDATE_PROJECT = 'UPDATE_PROJECT'
const DELETE_PROJECT = 'DELETE_PROJECT'

const NOTIFY = 'NOTIFY'

export { ADD_PROJECT, UPDATE_PROJECT, DELETE_PROJECT, NOTIFY }